name: Format Code and Create PR

on:
  push:
    branches:
      - main

jobs:
  format-and-pr:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install isort black

      # Get files changed in the last commit
      - name: Get changed files
        id: changed-files
        run: |
          git show --name-only --pretty="" HEAD > changed_files.txt
          cat changed_files.txt

      # Run isort and black
      - name: Run isort and black
        run: |
          if [ -s changed_files.txt ]; then
            grep '\.py$' changed_files.txt | xargs isort
            grep '\.py$' changed_files.txt | xargs black
          else
            echo "No changed files found."
          fi

      # Commit changes
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Apply isort and black formatting"
          else
            echo "No formatting changes to commit."
          fi

      # Push changes to a new branch
      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b code-format-through-bot
            git push origin code-format-through-bot
          fi

      # Create a PR for approval
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const branchName = 'code-format-through-bot';
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Code Formatting Updates',
              head: branchName,
              base: 'main',
              body: 'This PR applies isort and black formatting to the files changed in the last commit.',
            });
            console.log(`Created pull request: ${pullRequest.html_url}`);