name: Format Code, Create PR and Merge PRs for QA and Dev

on:
  pull_request:
    branches:
      - main
      - qa
      - dev
    types: [closed]

jobs:
  format-code:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'code-format-through-bot-')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install isort black

      - name: Get changed files
        id: changed-files
        run: git show --name-only --pretty="" HEAD | grep '\.py$' > changed_files.txt

      - name: Run isort and black
        run: |
          if [ -s changed_files.txt ]; then
            cat changed_files.txt | xargs isort
            cat changed_files.txt | xargs black
          else
            echo "No changed files found."
          fi

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[codeql-bot]"
            git config user.email "github-actions[codeql-bot]@users.noreply.github.com"
            git add --all :!changed_files.txt
            git commit -m "Apply isort and black formatting"
            echo "found_formatting_changes=true" >> $GITHUB_ENV
          else
            echo "No formatting changes to commit."
            echo "found_formatting_changes=false" >> $GITHUB_ENV

      - name: Upload changes
        if: env.found_formatting_changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: formatted-code
          path: .

  raise-and-merge-pr:
    runs-on: ubuntu-latest
    needs: format-code
    if: needs.format-code.outputs.found_formatting_changes == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download changes
        uses: actions/download-artifact@v3
        with:
          name: formatted-code
          path: .

      - name: Set branch name
        id: vars
        run: echo "BRANCH_NAME=code-format-through-bot-$(date +%s)" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = process.env.BRANCH_NAME;
            const branches = ['main', 'qa', 'dev'];
            for (const base of branches) {
              const { data: pullRequest } = await github.rest.pulls.create({
                owner: 'gmi-aashish',
                repo: 'test-branching-strategy',
                title: `Code Formatting Updates for ${base}`,
                head: branchName,
                base: base,
                body: 'This PR applies isort and black formatting to the files changed in the last commit.',
              });
              console.log(`Created pull request for ${base}: ${pullRequest.html_url}`);
            }

      - name: Merge PRs for qa and dev
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = process.env.BRANCH_NAME;
            const branches = ['qa', 'dev'];
            for (const base of branches) {
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: 'gmi-aashish',
                repo: 'test-branching-strategy',
                head: `gmi-aashish:${branchName}`,
                base: base,
                state: 'open',
              });
              for (const pr of pullRequests) {
                await github.rest.pulls.merge({
                  owner: 'gmi-aashish',
                  repo: 'test-branching-strategy',
                  pull_number: pr.number,
                });
                console.log(`Merged pull request for ${base}: ${pr.html_url}`);
              }
            }
