name: Merge Hotfix

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merge_hotfix:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'hot-fix'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune --unshallow

      - name: Merge main into QA
        run: |
          git checkout qa
          git pull origin qa
          git merge --no-ff --no-edit main
          git push origin qa

      - name: Merge main into Dev
        run: |
          git checkout dev
          git pull origin dev
          git merge --no-ff --no-edit main
          git push origin dev
