name: raise pull request to sync 'qa' with 'main'

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-qa-with-main:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up Git
        run: |
          git config user.name "gh-ac[sync-w-master-bot]"
          git config user.email "gh-ac[sync-w-master-bot]@users.noreply.github.com"

      - name: fetch all branches
        run: git fetch --prune --unshallow

      - name: get latest of 'main' in 'sync-qa-w-master'
        run: |
          git checkout -b sync-qa-w-main
          git pull origin main
          git push origin sync-qa-w-main

      - name: raise PR to merge 'main' into 'qa'
        uses: actions/github-script@v6
        with:
          script: |
            // collect all open pull requests
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'sync-qa-w-main',
              base: 'qa',
              state: 'open'
            });
            
            // create pull request if not exists
            if (pullRequests.length === 0) {
              const { data: pullRequest } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'pull request by gh-ac[sync-w-main-bot] - merge [main] into [qa]',
                head: 'sync-qa-w-main',
                base: 'qa',
                body: 'This is a [bot] PR to merge changes in [main] into [qa].',
              });
              console.log(`Created pull request: ${pullRequest.html_url}`);
              
              // merge the pull request automatically (with failure if not possible)
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                merge_method: 'merge'
              });
            } else {
              // add a new commit to the existing pull request
              console.log('A pull request already exists. New commit will be added to it.');
            }