name: sync lower branches with master

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-with-master:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'code-format-through-bot-')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "gh-ac[sync-w-master-bot]"
          git config user.email "gh-ac[sync-w-master-bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --prune --unshallow

      - name: Merge main into QA
        run: |
          git checkout qa
          git pull origin qa
          git merge --no-ff --no-edit -Xtheirs main # Merge main into QA, with the main branch changes taking precedence
          git push origin qa

      - name: Merge main into Dev
        run: |
          git checkout dev
          git pull origin dev
          git merge --no-ff --no-edit -Xtheirs main # Merge main into Dev, with the main branch changes taking precedence
          git push origin dev